name: "kcov-action"
author: williamdes
description: "Use Kcov without having to install it and generate your coverage"
inputs:
    cli-args:
        description: "Command line arguments"
        required: true

branding:
    icon: "umbrella"
    color: purple
runs:
    using: "docker"
    image: "docker://crubalcaba/kcov"
    args:
        - ${{ inputs.cli-args }}
